# Configuración de MySQL
DB_HOST = "sql10.freesqldatabase.com"
DB_NAME = "sql10798773"
DB_USER = "sql10798773"
DB_PASSWORD = "wpSy8rfz3D"
DB_PORT = 3306

# Configuración JWT
JWT_SECRET = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"

# Configuración SMTP para emails
SMTP_SERVER = "sandbox.smtp.mailtrap.io"
SMTP_PORT = 2525
SMTP_USERNAME = "7041e681befdf1"
SMTP_PASSWORD = "2ec4a059b1216c"
SMTP_USE_TLS = true
SMTP_FROM_NAME = "Biblioteca UNT"
SMTP_FROM_EMAIL = "no-reply@biblioteca.edu"

# Configuración de la aplicación
MAX_FILE_SIZE_MB = 5
ALLOWED_IMAGE_EXTENSIONS = "jpg,jpeg,png,gif"
APP_NAME = "Sistema de Gestión de Biblioteca"
APP_VERSION = "1.0.0"